services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: bootlab-backend
    restart: unless-stopped
    ports:
     - "5000:5000"
    env_file:
     - "./backend/.env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - bootlab-net
    
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
     - "6379:6379"
    volumes:
    - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
     - bootlab-net

volumes:
  redis-data:

networks:
  bootlab-net:
   driver: bridge 